apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: route-nas
    namespace: route-nas
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 14.1.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: route-nas
    values:
        ingress:
            main:
                enabled: true
                hosts:
                    - host: nas.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
        release_name: route-nas
        service:
            main:
                enabled: true
                type: ExternalIP
                externalIP: 192.168.1.2
                ports:
                    main:
                        enabled: true
                        port: 444
                        protocol: https
