apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 15m
  chart:
    spec:
      chart: pgadmin
      version: 16.1.4
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.111
        ports:
          main:
            port: 80
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PGADMIN_DEFAULT_EMAIL: "${DOMAIN_0_EMAIL}"
                PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    # persistence:
    #   config:
    #     enabled: true
    #     mountPath: /var/lib/pgadmin
    #     path: "${NFS_CONTAINERS_DATA_BASE}/pgadmin"
    #     server: "${NFS_SERVER}"
    #     type: nfs
    # securityContext:
    #   container:
    #     runAsUser: 5050
    #     runAsGroup: 5050
    #     fsGroup: 568
    persistence:
      init:
        enabled: true
        type: configmap
        objectName: init
        mountPath: "/pgadmin4/config_system.py"
        defaultMode: "0777"
        readOnly: true
        targetSelector:
          main:
            init: {}
    configmap:
      init:
        enabled: true
        data:
          config_system.py: |-
            X_CONTENT_TYPE_OPTIONS = ""    # default value is nosniff
            ENHANCED_COOKIE_PROTECTION = False
            X_XSS_PROTECTION = "0"  # default value is '1; mode=block'
