apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pgadmin
    namespace: pgadmin
spec:
    interval: 15m
    chart:
        spec:
            chart: pgadmin
            version: 16.1.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        # persistence:
        #   config:
        #     enabled: true
        #     mountPath: /var/lib/pgadmin
        #     path: "${NFS_CONTAINERS_DATA_BASE}/pgadmin"
        #     server: "${NFS_SERVER}"
        #     type: nfs
        service:
            main:
                type: LoadBalancer
                loadBalancerIP: 192.168.1.111
                ports:
                    main:
                        port: 80
        workload:
            main:
                podSpec:
                    containers:
                        main:
                            env:
                                PGADMIN_DEFAULT_EMAIL: '${DOMAIN_0_EMAIL}'
                                PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
        # persistence:
        #     init:
        #         enabled: true
        #         type: configmap
        #         objectName: init
        #         mountPath: '/pgadmin4/config_local.py'
        #         subPath: 'config_local.py'
        #         defaultMode: '0664'
        # configmap:
        #     init:
        #         enabled: true
        #         securityContext:
        #             runAsUser: 5050
        #             runAsGroup: 0
        #         data:
        #             config_local.py: |
        #                 X_CONTENT_TYPE_OPTIONS = ""    # default value is nosniff
        #                 ENHANCED_COOKIE_PROTECTION = False
        #                 X_XSS_PROTECTION = "0"  # default value is '1; mode=block'
        ingress:
            main:
                enabled: true
                # annotations:
                #     traefik.frontend.passHostHeader: true
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                hosts:
                    - host: pgadmin.${DOMAIN_0}
