apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: vaultwarden
    namespace: auth
spec:
    interval: 15m
    chart:
        spec:
            chart: vaultwarden
            version: 27.1.2
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        cnpg:
            main:
                password: ${CNPG_PASSWORD}
                user: vaultwarden
                # backups:
                #   credentials: minio
                #   enabled: true
                # recovery:
                #   method: object_store
                #   credentials: minio
        # credentials:
        #   minio:
        #     accessKey: ${S3_ACCESS_KEY}
        #     bucket: backup
        #     encrKey: ${S3_ENCR_KEY}
        #     name: minio
        #     path: ""
        #     secretKey: ${S3_SECRET_KEY}
        #     type: s3
        #     url: ${S3_URL}
        # persistence:
        #   data:
        #     enabled: true
        #     mountPath: /data
        #     volsync:
        #       - credentials: minio
        #         dest:
        #           enabled: true
        #         name: config
        #         src:
        #           enabled: true
        #         type: restic
        ingress:
            main:
                enabled: true
                hosts:
                    - host: vaultwarden.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                    #homepage:
                    #    enabled: true
                    #    group: System
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        vaultwarden:
            admin:
                disableAdminToken: false
                enabled: true
                token: ${VAULTWARDEN_PASSWORD}
            allowInvitation: true
            defaultInviteName: Vault hosted by ${DEFAULT_USER}
            enableWebVault: true
            icons:
                cache: 0
            orgCreationUsers: all
            push:
                enabled: false
                installationId: ${BWPUSHID}
                installationKey: ${BWPUSHKEY}
            requireEmail: true
            showPasswordHint: true
            signupwhitelistenable: false
            smtp:
                authMechanism: Plain
                enabled: true
                from: alerts@${DOMAIN_0}
                fromName: Vaultwarden
                host: smtp.ionos.fr
                password: ${SMTP_PASSWORD}
                port: 465
                security: force_tls
                user: ${DOMAIN_0_EMAIL}
            verifySignup: false
