apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mosquitto
    namespace: smarthome
spec:
    interval: 15m
    chart:
        spec:
            chart: mosquitto
            version: 15.0.10
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        auth:
            enabled: true
        persistence:
            configinc:
                enabled: true
                mountPath: /mosquitto/configinc
                path: '${NFS_CONTAINERS_DATA_BASE}/mosquitto/config'
                server: '${NFS_SERVER}'
                type: nfs
            data:
                enabled: true
                mountPath: /mosquitto/data
                path: '${NFS_CONTAINERS_DATA_BASE}/mosquitto/appData'
                server: '${NFS_SERVER}'
                type: nfs
