apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mhzyIY0mLtayCWuN/g7ACLMjntBH5HpzRj03Aktj9Jo3M2lhqltgsZSkEzoHLhtvKBubgCkIPFUqz5IidqQG8mwEYL5KhJMz1iSw77uMSgOIk60JtkclqBaa8Y+29rfY6YX7z0cYnpKn0MS6/nOlfo34feae2dr4AQbc5bx2dwV5+GhZ4scw/LgLm96oICPYdriRXuAbIznp6G2Mo60faFGmszaIJmRcr2qbXzhLaJ9dlUAJqPpVQER0ZDb8eZkOwr0i3C4uFmp7lL9rayQ5x1v6Oa7FW+r8Zaq2yruKldIVMbwHfwZXDuw3yUHooFpKycbrI6HK3f6LA7FqLdV/ATDcYQwmsY0gps3THIqnicBfPS9uYRcTT9SwfrSfKJql,iv:mvnOYLIMue3dZiQBSflozTPw/pnIlG6Ny/rtuP57RYI=,tag:uDO9v40Z5asD78Hc/6W5mA==,type:str]
    identity.pub: ENC[AES256_GCM,data:wruld4Xz1YE6UHHCtQ9SWtY2iYVfjgIiLKIfY/GQk0EsHzpN4+PmmumU4fbzT7C/UPXK+j/L7h7bAjImu4ku4LpLJp6S0MSI9GNZOUZo/rImN8giFMS9va9dzx/NRLlktjV1jMDiilA1ZoxObOVKm1akOylHXHsuCkfKAipxlcjChOB4E9/p1B9uEAa7nHGBZNCY+DuGgu9u3Q4rzj+74ZiE2aD3tScwb1FupDbw/lJLpiQMncl3WrD2HiqplKVlNMENhrNfV62Vqf7LdA==,iv:4YkKqGsXKLr6ZtSjeMHai8J1wZ5U5F5XqZ8JS9XEPWQ=,tag:NNDddYQ2nps4WpK1F3AHUg==,type:str]
    known_hosts: ENC[AES256_GCM,data:BMZZ5cc9CVZJkel/qQc062Z7H4CrgF6k1APQ6aFmRYfTBsl0osMNnQpFRmn2CtWm3Z6xnyXRJaNgjihz8UcBv+PSOSaf8HHzvMj38JRB5I0t1hBar3ZfGlQaor26KJpEY2XUOSewkzAtY3nrrDo3TyABEVD84sfoPvQVyEPrz2H0S6QUnMJzvgLP6sx46AfARQiWBR4Kyu5SlHT2q0ONRKkHWUpddKIZFZTF,iv:1hEs6AkzgsEn13wyGBcNSPezzx6nrob8u0M8WDya3is=,tag:jgfs1wGxV/Nm57hx95yXJw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ntjhr0ag7pppnm926urp927zpkwz4tx9cy8umrx38wdkg0n2p5ysyz3ra3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdis1cDk1d0VreFZ6Wm9w
            UUNyV0FhazF3M3dJV1pXMmhXVW56Y0FMVEVvCnhGbmRKeGhJZGNNWjdRTlQ5RmJ3
            ME13YS9TV2ZLSUZSN1c1L0ltVzZHZ2cKLS0tIHRwdzRIa2VINmtmS2g3ZnhkeEhh
            Ni9pQjhYb25mTlZUZGRBWTU2OUw5aGMKWewcvkHx2hczJuuAV83XleCbEcePCQL4
            X2HZSaz7XgyaTObNTmRZMwVrtH+BRmeZDGXs8EbKYPDxyYlGwH9AlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T19:48:08Z"
    mac: ENC[AES256_GCM,data:UagATFAFyqldVkGqT/TCaZ12DUCRxz4nHVhANUb/ugYEOcO8e0GToxZEqtzm7w4GRUlszmlJLP/TvY4XZfA2ZM8flAVsYz9ENVfcoTSAsYbMr3ygH/PbOsKJq14qP3iSPs7EJlssrATutrApulQHcXEIJBIhximFg7NDjVnl/Yo=,iv:6L/91dymKi5xHbJiyCPFh5tayaz4TQLMJBBMrFdsIho=,tag:UEKHXBhVTAcBBspr80pm9Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
