apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:f1tXhWb8fxpG7wnKz1kKmTyJcV4uYw7nGPj1mp+zwHgO00ruP+MEs2H6mi7jsPfmhbs8UqzeXsW6DraUGm9PQzVIYxQBJKtcFTV+ChqxSydESV/51xxcyeo3C1cwTijH1OGcPSt3jAlRsIOy0Kum9s1aPUvBhdAJhl7170GbdMxn5NFGaj7OGID3OgOZxlwuD050fpMr8HMEv8btp6RJlpPbtkge7qEJoofR/8W4tOtiOOSllOJhIzZlb3o1i3Qfb9yFx+4Iy9nvEMeuhJiOn9lNs2cixDQpIovzera5U89sZ1F61VmaOaRjZe4dah6p7r/YBfQUxcnw3BX2iuz87jrPfkWOpypEofQ8DpfX2KOV6Q3SKe3WxIcp8XaHw8h8,iv:Z+ud9v8VDUeBme78vZBJiC1xoNcyXEo8ESx3nlq0ErA=,tag:MdVSY6fE5KzlsupekRskfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:jSyNXLzM9K7t5ysvxsJtb78NvQXHuKykZ8o1gXGoJOsuXXOSTlmrn0ZxaJkMVBDFnoFxC7Q8zGOIMx1KrO6dUXFUuCGnwWupwIzbxR3avBSKyfMi/wLXAa9raWMzkGeh64e13ydg50ukScE+lPooGROnSYzHiOe6AjXYaHGjYjLQqfv4vFRRsE1PbO8aRGT69AG2cn/kEO7Wa5FNXfkvk580a9+2RYo7Ql+zJuz7h0LFDu+m0GTEL9+vI9i+91ejM2RoXFrf8dEOm895QA==,iv:XvPZNeMnY6feIYUhiIrI04FHvVJjjn9SbF+2JcDD358=,tag:9aisbYPGx8xzeYI84o/cnA==,type:str]
    known_hosts: ENC[AES256_GCM,data:KYRWVhRkE+208yk2O4UMSetEtHgb2+UvPeiLuifRyOCkPWjES5WjncgQl3WnSweUi5GIyKmQp8N2E5PmkdN4s/5umIwQc9tRXh7LQRlpZ2AN4Kd+SJxc/f38oONWAOJZe2YO+O6ev82UiQhbvr1dN/RhvT7bHf/C4wXTkGT4S8R/xrZdsuv+rtPWcpidFaPntG9egOBk/0bvpTS2y74cUa5sy1lYMONvRlpl,iv:Z1oaLxbWKMtMzoEn6+VEWl64j7erb6UDnaa/qFu3nk4=,tag:+gngUl1CNeqXypKANeXOYg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ntjhr0ag7pppnm926urp927zpkwz4tx9cy8umrx38wdkg0n2p5ysyz3ra3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbU92U2JBOEw0V1lkdWQw
            RWwzNWhNcktjRGxsTFJUMFJmWGRPZmxSQkFZCkNZdzlQZHU3UlpiMGc4WVZRVlhZ
            dnp6SXkyNVBqeFJYOFB1NmtsQkxSZ00KLS0tIEhpMyswU1ZHV1VWWUF5T0hJblBj
            T3JJNGFoRzk2NHEvUmZwV2pqamdyWEUKuGNzH9AjD/JfMITO61RtBn5H9KxxM3q+
            T4UCJo9eSrOwnm/BJHy1T9H918SelLQZK6rFwa/ndlOcC0IMRBRN6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-01T09:39:24Z"
    mac: ENC[AES256_GCM,data:IEL4FzgR99zZnOhNyjj4ZdyccVdUJdOf4WCpWFTf76v8vU3Ei11GPwnw0lEj7iwi8L9OJsGy4Zhrxh1V2108+2Q2844MmDEsoWCNDs7xb+E1fLk0VQ0q5UL+FDPO3W/kafF3v127pWnumElyGgIOaBcXIBjBuq06yPYPJaWzyiQ=,iv:/aLIt3v9DBJGU5XfE3nPU5YNQ8evq7HGW66I8W+l0pc=,tag:f/EYHKd+JxbAz504ziot8A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
