apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: dockerregistry
    namespace: dockerregistry
spec:
    interval: 15m
    chart:
        spec:
            chart: dockerregistry
            version: 6.0.10
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        ingress:
            main:
                enabled: true
                integrations:
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                hosts:
                    - host: registry.${DOMAIN_0}
        persistence:
            datastoragepath:
                enabled: true
                mountPath: /var/lib/registry
                path: /mnt/TestPool/share/docker_imgs
                server: '${NFS_SERVER}'
                type: nfs
