apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dockerregistry
  namespace: dockerregistry
spec:
  interval: 15m
  chart:
    spec:
      chart: dockerregistry
      version: 6.0.10
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  releaseName: dockerregistry
  values:
    # Disabled until I go back home and verify it works
    # ingress:
    #     main:
    #         enabled: true
    #         integrations:
    #             traefik:
    #                 enabled: true
    #                 entrypoints:
    #                     - websecure
    #             certManager:
    #                 certificateIssuer: "${DOMAIN_0}-prod"
    #                 enabled: true
    #         hosts:
    #             - host: codeserver.${DOMAIN_0}
    #               paths:
    #                   - path: /
    #                     pathType: Prefix
    # Temporary until I go back home
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.106
        ports:
          main:
            port: 80
    persistence:
      datastoragepath:
        enabled: true
        mountPath: /var/lib/registry
        path: /mnt/TestPool/share/docker_imgs
        server: 192.168.1.2
        type: nfs