apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: home-assistant
    namespace: smarthome
spec:
    interval: 15m
    chart:
        spec:
            chart: home-assistant
            version: 25.1.8
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: home-assistant
    values:
        ingress:
            main:
                enabled: true
                hosts:
                    - host: home.${DOMAIN_0}
                integrations:
                    certManager:
                        certificateIssuer: '${DOMAIN_0_BASE}-prod'
                        enabled: true
                    #homepage:
                    #    enabled: true
                    #    group: Smart Home
                    traefik:
                        allowCors: false
                        enabled: true
                        entrypoints:
                            - websecure
        cnpg:
            main:
                enabled: true
                user: home-assistant
                password: ${CNPG_PASSWORD}
                database: home-assistant
                # backups:
                #     credentials: minio
                #     enabled: true
                # recovery:
                #     enabled: false
                # cluster:
                #     instances: 1
                #     singleNode: true
        # credentials:
        #     minio:
        #         accessKey: ${S3_ACCESS_KEY}
        #         bucket: backup
        #         encrKey: ${S3_ENCR_KEY}
        #         name: minio
        #         secretKey: ${S3_SECRET_KEY}
        #         type: s3
        #         url: ${S3_URL}
        persistence:
            config:
                enabled: true
                mountPath: /config
                path: ${NFS_CONTAINERS_DATA_BASE}/ha/config
                readOnly: false
                server: 192.168.1.2
                targetSelectAll: true
                type: nfs
        securityContext:
            container:
                capabilities:
                    add: []
